---
- name: Copy app
  template:
    src: plop.py.j2
    dest: /root/plop.py
    mode: 0755
  
- name: Copy service
  template:
    src: plop.service.j2
    dest: /etc/systemd/system/plop.service

- name: Enabling service
  service:
    name: plop
    state: started
    enabled: true
