---
- name: Install haproxy
  package:
    name: haproxy

- name: Copy template
  template:
    src: haproxy.cfg.j2
    dest: "/etc/haproxy/haproxy.cfg"
  notify: Reload haproxy

- name: Run haproxy
  service:
    name: haproxy
    state: started
    enabled: yes
