# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define :vm, autostart: true do |myvm|
    myvm.vm.box = "centos/7"
    myvm.vm.box_version = "1905.1"
    myvm.vm.hostname = "vm"
    myvm.vm.network "private_network", ip: "192.168.201.9"
  end
end
