---
- name: Delete default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx
- name: Copy template
  template:
    src: vhost.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ nginx_vhost_target_host }}.conf"
  notify: Reload nginx