---
- name: desactive la connexion ssh pour root
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify:
    - restart sshd

- name: desactive la connexion ssh avec mot de passe
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify:
    - restart sshd

- name: desactive la résolution DNS pour SSH (lent)
  lineinfile: dest=/etc/ssh/sshd_config regexp="^UseDNS" line="UseDNS no" state=present
  notify:
    - restart sshd

- name: desactive l'authent GSSAPI (Kerberos) pour SSH (lent)
  lineinfile: dest=/etc/ssh/sshd_config regexp="^GSSAPIAuthentication" line="GSSAPIAuthentication no" state=present
  notify:
    - restart sshd
